### ISSUE TITLE
Release on Modrinth

### ISSUE THREAD

**Issue by aquifolly** [catppuccin/minecraft#16]
https://modrinth.com/resourcepacks

**Comment by unseen-ninja** [comment]
Very descriptive; thanks! ^—^

That aside, I'd be in favour of this. Love Modrinth! <3
**But** I# not sure if it's possible to release things there as an Org. I'll look into it if you don't mind @Aurn1ox?

**Comment by unseen-ninja** [comment]
> **MattiDragon** — _Today at 15:03_
You can currently not log in as an organization, but you can create the project on a personal account and make the others members.

So, yeah. That's a bummer, but I worried that this would be the case. :/

**Comment by hellholesys** [comment]
could always do what quilt does with the @quilt-holdings account, and just have a personal account to represent the org when a github org isnt sufficient

**Comment by osfanbuff63** [comment]
Yeah, the (GH) TOS allows that - assuming you don't already have one haha

**Comment by JustLetterV** [comment]
👍 Modrinth is awesome, would make releasing/downloading different versions way easier :)

**Comment by aquifolly** [comment]
and it'll be even better once launchers like prism get resource pack downloading

**Comment by JustLetterV** [comment]
Catppuccin UI is now available at https://modrinth.com/resourcepack/catppuccin-ui for all Minecraft versions from 1.6.1 to 1.19.4 :)
