### ISSUE TITLE
Only UI?

### ISSUE THREAD

**Issue by t0msk** [catppuccin/minecraft#18]
Hello,

is possible to install this theme only for UI? Not for blocks?

**Comment by JustLetterV** [comment]
Hi @t0msk this resource pack only affects UI, make sure you don't have any other pack enabled that makes changes to blocks :) Or if you are using the shader pack and want only UI to be themed then you can switch to using the Catppuccin UI resource pack which can be downloaded on our [Modrinth page](https://modrinth.com/resourcepack/catppuccin-ui).

**Comment by t0msk** [comment]
@mvilk thank you :)
