### ISSUE TITLE
Appleskin

### ISSUE THREAD

**Issue by BoostAteHisDog** [catppuccin/minecraft#19]
You should add appleskin support

**Comment by JustLetterV** [comment]
Hello, support for appleskin will be added in the next release which I'm already working on, thank you for the request :)

**Comment by BoostAteHisDog** [comment]
Tysm!

**Comment by BoostAteHisDog** [comment]
do you have a planned release date @mvilk?

**Comment by JustLetterV** [comment]
No planned release date, I'll release it when it's ready

**Comment by BoostAteHisDog** [comment]
ok!

**Comment by JustLetterV** [comment]
Added in version 1.1.0, can be downloaded from Modrinth
