### ISSUE TITLE
Mod support for bedrockify?

### ISSUE THREAD

**Issue by knsolrk** [catppuccin/minecraft#20]
Bedrockify is a mod that ports various bedrock edition features to java edition

https://modrinth.com/mod/bedrockify

Right now it only uses one custom texture so [pretty please :3c](https://github.com/juancarloscp52/BedrockIfy/blob/1.19/src/main/resources/assets/bedrockify/textures/gui/bedrockify_widgets.png)

![imagen](https://github.com/catppuccin/minecraft/assets/91399973/48fae6ef-22e4-4753-8524-88d2ac3717b9)

**Comment by JustLetterV** [comment]
Hi, will be added in the next release, no ETA though

**Comment by JustLetterV** [comment]
Added in version 1.1.0, can be downloaded from Modrinth
