### ISSUE TITLE
[Mod support] No chat reports

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/minecraft#21]
Probably one of the most used mods ever. It would be nice to have the few buttons it has in the server menu themed

**Comment by JustLetterV** [comment]
Should already be themed in version 1.0.0. Which version of Minecraft and resource pack are you using?
![image](https://github.com/catppuccin/minecraft/assets/75657829/2da35c73-de32-4fed-9463-520056d63b02)
Edit: Icons in the buttons are not fully themed, I could do that for the next release.

**Comment by CallMeEchoCodes** [comment]
yeah i was thinking the icons. the buttons are already themed

**Comment by JustLetterV** [comment]
Added in version 1.1.0, can be downloaded from Modrinth
