### ISSUE TITLE
[Mod support] Trinkets

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/minecraft#22]
Again a very popular mod. Inventories look weird with it installed.

**Comment by JustLetterV** [comment]
Will be added in the next release 👍

**Comment by JustLetterV** [comment]
Added in version 1.1.0, can be downloaded from Modrinth. There was one issue. Glove slot borders look like this and I believe that this can't be fixed
![image](https://github.com/catppuccin/minecraft/assets/75657829/55fe9481-67f4-4868-bc2c-d276d633e759)
