### ISSUE TITLE
[Mod Support] ExpandedStorage

### ISSUE THREAD

**Issue by CassieRoseZA** [catppuccin/minecraft#25]
Could we potentially get mod support for Expanded Storage as its a mod i use quite often and just seeing the white makes it look out of place from my inventory

**Comment by JustLetterV** [comment]
Heya, added in v1.2.0 which is now available on Modrinth :) There are few minor issues:
1. When using the paginated screen type, the page number text color is wrong and the last page might have weird lines. Look at the image below
2. Also, when enabling/disabling the pack while in world/server, you'll have to relog to see container name colors update.
![image](https://github.com/catppuccin/minecraft/assets/75657829/96d21fa8-f02b-4d45-b92a-e681bda97a08)

If you encounter any other problems than the ones mentioned above create a new issue :)
