### ISSUE TITLE
[Mod Support] Screenshot Viewer

### ISSUE THREAD

**Issue by 10kmotorola** [catppuccin/minecraft#26]
Wonderful theme, just wondering if we could potentially get support for [Screenshot Viewer](https://modrinth.com/mod/screenshot-viewer)? Thanks for the work on the resource pack :D

**Comment by JustLetterV** [comment]
Thanks and you're welcome :D
Support for Screenshot Viewer has been added in the latest version (v1.2.0) now available on Modrinth. If you encounter any problems create a new issue :)
