### ISSUE TITLE
[ModSupport] TooltipTexture

### ISSUE THREAD

**Issue by Nyameliaaaa** [catppuccin/minecraft#27]
With this mod, we'll be able to finally fix the issue of tooltips not being consistent with Catppuccin :D 
Mod Link: https://github.com/moehreag/TooltipTexture

**Comment by JustLetterV** [comment]
Support for TooltipTexture has been added in the latest version (v1.2.0) now available on Modrinth. If you encounter any problems create a new issue :)

**Comment by Nyameliaaaa** [comment]
thank you!
