### ISSUE TITLE
Broken in 1.20.2

### ISSUE THREAD

**Issue by ameoverflow** [catppuccin/minecraft#31]
Minecraft 1.20.2 changed how GUI textures are stored inside of a resource pack, eg. splitting `textures/gui/widgets.png` to multiple files inside of `textures/gui/sprites/widget` with corresponding .mcmeta files if needed, thus rendering the pack incompatible with 23w31a (pack format 16) and newer. Mojang has released a tool to split old GUI textures into new GUI textures.

**Comment by Regnander** [comment]
> Mojang has released a tool to split old GUI textures into new GUI textures.

~~Link?~~

[Never mind – I found it!](https://github.com/Mojang/slicer/)

**Comment by JustLetterV** [comment]
I started the upgrade to the new version yesterday and plan to finish it today

**Comment by JustLetterV** [comment]
The 1.20.2 version is now available on Modrinth :)
