### ISSUE TITLE
1.20.4?

### ISSUE THREAD

**Issue by CassieRoseZA** [catppuccin/minecraft#34]
Can you update this pack for 1.20.4?

**Comment by JustLetterV** [comment]
I'm busy this week, but I'll look into this at the start of the next week. There shouldn't be many changes needed so it's probably quick update. Have you tried using the 1.20.2 version? If you have and encountered issues listing them here would help with the update to 1.20.4

**Comment by JustLetterV** [comment]
Update now available on Modrinth :)
