### ISSUE TITLE
Make a resourcepack generation system

### ISSUE THREAD

**Issue by thismoon** [catppuccin/minecraft#8]
instead of having 4 separate resourcepacks make 1 template resourcepack and a script to generate other resourcepacks from the template
this can be helpful if you want to edit something once instead of editing it 4 times with different colors
here's an example of a template texture
![inventory template](https://user-images.githubusercontent.com/107642606/209524408-4801b0b5-3e66-4856-b015-e0b29f0983b5.png)
the script will replace the colors with catppuccin colors and zip the folder
I can help with the script, and maybe even automate the creation of the template resourcepack with a script that does the opposite
this is similar to the Puccinier tools but it works for images

**Comment by Aurn1ox** [comment]
Oh thats similar to how i converted my packs from mocha to the other flavors, though i had to manually modify some stuff like the inventory icons so i didnt really think of that. my older method was probably not that good anyway but i can send it to you if you want.

**Comment by thismoon** [comment]
no thanks, I'll fork the repo and do it, probably with python

**Comment by Aurn1ox** [comment]
i actually used this script, and used the bash file to loop through every file if you're interested in what i did before.
[python script](https://raw.githubusercontent.com/catppuccin/minecraft/d3a44c0bef4b41882c047edae888020387ef80ff/extras)/scripts/color.py
[bash script](https://raw.githubusercontent.com/catppuccin/minecraft/d3a44c0bef4b41882c047edae888020387ef80ff/extras/scripts/color.sh)

**Comment by thismoon** [comment]
oh thanks, I didn't know that you did exactly what i was going to do
so no need of 2 hours of making python scripts
but shouldn't the script be included in the repo?

**Comment by Aurn1ox** [comment]
it used to be, but that script wasnt really that helpful after making the packs since you would still have to manually edit some parts of the pack which i decided were easier to do by hand than including a script for it, but if you manage to create a script to completely automate it that would be good too!
